Server:
      name: spring boot concepts
      port: 6364


      
management:
      endpoints:
         web:
           exposure:
              include: "*"                      
       


info:
  application:
     name: My Test spring boot app
     description: learning all spring boot concepts
     releaseInfo: build1.7
     
     
#---------------------H2 DB config----------------------------------------------------------------------
spring:
   datasource:
            url: jdbc:h2:mem:testdb
            #url: jdbc:h2:mem:file:D:/h2-db/data
            driverClassName: org.h2.Driver
            username: sa
            password: password
   jpa:
     show-sql: true
     
     properties:
                 hibernate:
                           dialect: org.hibernate.dialect.H2Dialect
     hibernate:
              ddl-auto: update
   h2:
     console:
           enabled: true
           path: /h2-console
           setting:
                   trace: false
                   web-allow-others: false
 
 
  # autoconfigure:
  #              exclude[0]: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  #               exclude[1]: org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
                   
  #--------------------------------------------------------------------------------------------------               

